# Generated by Django 3.2.4 on 2021-09-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
